[database]
user = "admin"
password = "admin"
[passwords]
"admin" = "admin"
"user1" = "admin123"
"guest" = "htwl2024"
[coze_api]
access_token = "pat_ZWJWBx8O7dvQkmD8j4mlJKSGeC8ILRTJsk7mANm4rIeqhPSsaL6tMCrWZMkIDLKV"
bot_id = "7434791541048655922"

[zhipu_api]
key = "3e21d6e293772009ea6b211a18ad3c8e.Z8xS7txXcdj7zAEU"
